--���̺� ����
--DDL
CREATE TABLE TBL_TICKET (
    TICKET_ID VARCHAR2(10) NOT NULL,
    TICKET_TYPE VARCHAR2(20) NOT NULL,
    TICKET_HOUR VARCHAR2(20) NOT NULL,
    TICKET_PRICE VARCHAR2(20) NOT NULL,
    TICKET_REG_DATE DATE NOT NULL,
    CAFE_NO VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN TBL_TICKET.TICKET_ID IS '�̿�� ���̵�';
COMMENT ON COLUMN TBL_TICKET.TICKET_TYPE IS '�̿�� ����';
COMMENT ON COLUMN TBL_TICKET.TICKET_HOUR IS '�̿�� �ð�';
COMMENT ON COLUMN TBL_TICKET.TICKET_PRICE IS '�̿�� ����';
COMMENT ON COLUMN TBL_TICKET.TICKET_REG_DATE IS '�̿�� �����';
COMMENT ON COLUMN TBL_TICKET.CAFE_NO IS '��ü��ȣ';

ALTER TABLE TBL_TICKET ADD CONSTRAINT PK_TBL_TICKET PRIMARY KEY (TICKET_ID);


CREATE TABLE TBL_CODE (
    CODE_ID VARCHAR2(30) NOT NULL,
    CODE_NAME VARCHAR2(30) NOT NULL,
    CODE_PARENT VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN TBL_CODE.CODE_ID IS '�ڵ���̵�';
COMMENT ON COLUMN TBL_CODE.CODE_NAME IS '�ڵ��';
COMMENT ON COLUMN TBL_CODE.CODE_PARENT IS '�θ��ڵ���̵�';

ALTER TABLE TBL_CODE ADD CONSTRAINT PK_TBL_CODE PRIMARY KEY (CODE_ID);


CREATE TABLE TBL_TICKET_HIST (
    HIST_CHANGE_NUMBER VARCHAR2(10) NOT NULL,
    HIST_TICKET_PRICE VARCHAR2(10) NOT NULL,
    HIST_TICKET_TIME VARCHAR2(10) NOT NULL,
    HIST_TICKET_CHANGE_DATE DATE NOT NULL,
    HIST_TICKET_ID VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN TBL_TICKET_HIST.HIST_CHANGE_NUMBER IS '������ȣ';
COMMENT ON COLUMN TBL_TICKET_HIST.HIST_TICKET_PRICE IS '���� �� ����';
COMMENT ON COLUMN TBL_TICKET_HIST.HIST_TICKET_TIME IS '���� �� �ð�';
COMMENT ON COLUMN TBL_TICKET_HIST.HIST_TICKET_CHANGE_DATE IS '��������';
COMMENT ON COLUMN TBL_TICKET_HIST.HIST_TICKET_ID IS '�̿�� ���̵�';

ALTER TABLE TBL_TICKET_HIST ADD CONSTRAINT PK_TBL_TICKET_HIST PRIMARY KEY (HIST_CHANGE_NUMBER);


CREATE TABLE TBL_CAFE (
    CAFE_NO VARCHAR2(10) NOT NULL,
    CAFE_NAME VARCHAR2(100) NOT NULL,
    CAFE_PHONE VARCHAR2(13) NOT NULL,
    CAFE_ADDR VARCHAR2(200) NOT NULL,
    CAFE_BIZNUM CHAR(12) NOT NULL,
    CAFE_INTRODUCE VARCHAR2(600) NOT NULL,
    CAFE_START_HOUR VARCHAR2(50) NOT NULL,
    CAFE_END_HOUR VARCHAR2(50) NOT NULL,
    CAFE_STATUS CHAR(1) DEFAULT 'N' NOT NULL,
    CAFE_INTRO_DETAIL VARCHAR2(500) NOT NULL,
    HOST_ID VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN TBL_CAFE.CAFE_NO IS '��ü��ȣ';
COMMENT ON COLUMN TBL_CAFE.CAFE_NAME IS '��ü��';
COMMENT ON COLUMN TBL_CAFE.CAFE_PHONE IS 'ī�� ��ȭ��ȣ';
COMMENT ON COLUMN TBL_CAFE.CAFE_ADDR IS '��ü �ּ�';
COMMENT ON COLUMN TBL_CAFE.CAFE_BIZNUM IS '����� ��� ��ȣ';
COMMENT ON COLUMN TBL_CAFE.CAFE_INTRODUCE IS '�Ұ���';
COMMENT ON COLUMN TBL_CAFE.CAFE_START_HOUR IS '���� ���� �ð�';
COMMENT ON COLUMN TBL_CAFE.CAFE_END_HOUR IS '���� ���� �ð�';
COMMENT ON COLUMN TBL_CAFE.CAFE_STATUS IS '�����(Y,N)';
COMMENT ON COLUMN TBL_CAFE.CAFE_INTRO_DETAIL IS '�����Ұ�';
COMMENT ON COLUMN TBL_CAFE.HOST_ID IS 'ȣ��Ʈ���̵�';

ALTER TABLE TBL_CAFE ADD CONSTRAINT PK_TBL_CAFE PRIMARY KEY (CAFE_NO);


CREATE TABLE TBL_HISTORY (
    HISTORY_ID VARCHAR2(10) NOT NULL,
    HISTORY_START DATE NOT NULL,
    HISTORY_END DATE NOT NULL,
    HISTORY_CAFE_NO VARCHAR2(10) NOT NULL,
    HISTORY_SEAT_NO VARCHAR2(10) NOT NULL,
    HISTORY_TICKET_ID VARCHAR2(10) NOT NULL,
    HISTORY_USER_ID VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN TBL_HISTORY.HISTORY_ID IS '������ȣ';
COMMENT ON COLUMN TBL_HISTORY.HISTORY_START IS '����������';
COMMENT ON COLUMN TBL_HISTORY.HISTORY_END IS '��� ��������';
COMMENT ON COLUMN TBL_HISTORY.HISTORY_CAFE_NO IS '��ü��ȣ';
COMMENT ON COLUMN TBL_HISTORY.HISTORY_SEAT_NO IS '�¼���ȣ';
COMMENT ON COLUMN TBL_HISTORY.HISTORY_TICKET_ID IS '�̿�� ���̵�';
COMMENT ON COLUMN TBL_HISTORY.HISTORY_USER_ID IS '�Ϲ� ����� ���̵�';

ALTER TABLE TBL_HISTORY ADD CONSTRAINT PK_TBL_HISTORY PRIMARY KEY (HISTORY_ID);


CREATE TABLE TBL_USER_REPORT (
    REPORT_ID VARCHAR2(20) NOT NULL,
    REPORTER_ID VARCHAR2(10) NOT NULL,
    TARGET_COMMENT_ID VARCHAR2(20) NOT NULL,
    REPORT_CODE_ID VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN TBL_USER_REPORT.REPORT_ID IS '�Ű��ȣ';
COMMENT ON COLUMN TBL_USER_REPORT.REPORTER_ID IS '�̿��� ���̵�';
COMMENT ON COLUMN TBL_USER_REPORT.TARGET_COMMENT_ID IS '�� ���̵�';
COMMENT ON COLUMN TBL_USER_REPORT.REPORT_CODE_ID IS '�Ű�����ڵ�';

ALTER TABLE TBL_USER_REPORT ADD CONSTRAINT PK_TBL_USER_REPORT PRIMARY KEY (REPORT_ID);


CREATE TABLE TBL_IMAGE (
    IMAGE_NO VARCHAR2(10) NOT NULL,
    CAFE_NO VARCHAR2(10) NOT NULL,
    IMAGE_NAME VARCHAR2(200) NOT NULL,
    IMAGE_PATH VARCHAR2(300) NOT NULL
);

COMMENT ON COLUMN TBL_IMAGE.IMAGE_NO IS '�̹��� ��ȣ';
COMMENT ON COLUMN TBL_IMAGE.CAFE_NO IS '��ü��ȣ';
COMMENT ON COLUMN TBL_IMAGE.IMAGE_NAME IS '�̹��� ���� �̸�';
COMMENT ON COLUMN TBL_IMAGE.IMAGE_PATH IS '�̹��� ���';

ALTER TABLE TBL_IMAGE ADD CONSTRAINT PK_TBL_IMAGE PRIMARY KEY (IMAGE_NO);


CREATE TABLE TBL_HOST_REQUEST (
    APPLY_NO NUMBER NOT NULL,
    APPLY_DATE DATE NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'N' NOT NULL,
    REJECT_ID VARCHAR2(30) NULL,
    HOST_NO VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN TBL_HOST_REQUEST.APPLY_NO IS '��û��ȣ';
COMMENT ON COLUMN TBL_HOST_REQUEST.APPLY_DATE IS '��û��';
COMMENT ON COLUMN TBL_HOST_REQUEST.STATUS IS '���ο���(Y,N)';
COMMENT ON COLUMN TBL_HOST_REQUEST.REJECT_ID IS '�ݷ������ڵ�';
COMMENT ON COLUMN TBL_HOST_REQUEST.HOST_NO IS '��ü ��ȣ';

ALTER TABLE TBL_HOST_REQUEST ADD CONSTRAINT PK_TBL_HOST_REQUEST PRIMARY KEY (APPLY_NO);


CREATE TABLE TBL_USER (
    USER_ID VARCHAR2(10) NOT NULL,
    USER_PW VARCHAR2(12) NOT NULL,
    USER_ROLE NUMBER DEFAULT 3 NOT NULL,
    USER_PHONE VARCHAR2(13) NOT NULL,
    USER_STATUS CHAR(1) DEFAULT 'N' NOT NULL,
    USER_IMAGE VARCHAR2(100)
);

COMMENT ON COLUMN TBL_USER.USER_ID IS '�̿��� ���̵�';
COMMENT ON COLUMN TBL_USER.USER_PW IS '�̿��� ��й�ȣ';
COMMENT ON COLUMN TBL_USER.USER_ROLE IS '�̿��� ����';
COMMENT ON COLUMN TBL_USER.USER_PHONE IS '�̿��� ��ȭ��ȣ';
COMMENT ON COLUMN TBL_USER.USER_STATUS IS 'ȣ��Ʈ ��û����';
COMMENT ON COLUMN TBL_USER.USER_IMAGE IS '�̿��� ������ ����';

ALTER TABLE TBL_USER ADD CONSTRAINT PK_TBL_USER PRIMARY KEY (USER_ID);


CREATE TABLE TBL_COMMENT (
    COMMENT_ID VARCHAR2(20) NOT NULL,
    TARGET_TYPE VARCHAR2(3) NOT NULL,
    CONTENT VARCHAR2(500) NOT NULL,
    COMMENT_TIME DATE NOT NULL,
    COMMENT_USER_ID VARCHAR2(10) NOT NULL,
    COMMENT_CAFE_NO VARCHAR2(10) NOT NULL,
    COMMENT_PARENT VARCHAR2(500)
);

COMMENT ON COLUMN TBL_COMMENT.COMMENT_ID IS '�� ���̵�';
COMMENT ON COLUMN TBL_COMMENT.TARGET_TYPE IS '�������';
COMMENT ON COLUMN TBL_COMMENT.CONTENT IS '�� ����';
COMMENT ON COLUMN TBL_COMMENT.COMMENT_TIME IS '�ۼ��ð�';
COMMENT ON COLUMN TBL_COMMENT.COMMENT_USER_ID IS '�̿��� ���̵�';
COMMENT ON COLUMN TBL_COMMENT.COMMENT_CAFE_NO IS '��ü��ȣ';
COMMENT ON COLUMN TBL_COMMENT.COMMENT_PARENT IS '�θ��� ���̵�';

ALTER TABLE TBL_COMMENT ADD CONSTRAINT PK_TBL_COMMENT PRIMARY KEY (COMMENT_ID);


CREATE TABLE TBL_PAY_HISTORY (
    PAY_ID NUMBER NOT NULL,
    PAY_TIME DATE NOT NULL,
    PAY_STATUS VARCHAR2(10) NOT NULL,
    PAY_AMOUNT VARCHAR2(10) NOT NULL,
    PAY_METHOD VARCHAR2(10) NOT NULL,
    PAY_USER_ID VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN TBL_PAY_HISTORY.PAY_ID IS '�������̵�';
COMMENT ON COLUMN TBL_PAY_HISTORY.PAY_TIME IS '���� �ð�';
COMMENT ON COLUMN TBL_PAY_HISTORY.PAY_STATUS IS '���� ����';
COMMENT ON COLUMN TBL_PAY_HISTORY.PAY_AMOUNT IS '���� �ݾ�';
COMMENT ON COLUMN TBL_PAY_HISTORY.PAY_METHOD IS '���� ����';
COMMENT ON COLUMN TBL_PAY_HISTORY.PAY_USER_ID IS '�̿��� ���̵�';

ALTER TABLE TBL_PAY_HISTORY ADD CONSTRAINT PK_TBL_PAY_HISTORY PRIMARY KEY (PAY_ID);

--FK ����
-- TBL_TICKET �� TBL_CAFE
ALTER TABLE TBL_TICKET
ADD CONSTRAINT FK_TICKET_CAFE FOREIGN KEY (CAFE_NO)
REFERENCES TBL_CAFE (CAFE_NO);

-- TBL_TICKET_HIST �� TBL_TICKET
ALTER TABLE TBL_TICKET_HIST
ADD CONSTRAINT FK_TICKET_HIST_TICKET FOREIGN KEY (HIST_TICKET_ID)
REFERENCES TBL_TICKET (TICKET_ID);

-- TBL_CAFE �� TBL_USER
ALTER TABLE TBL_CAFE
ADD CONSTRAINT FK_CAFE_HOST FOREIGN KEY (HOST_ID)
REFERENCES TBL_USER (USER_ID);

-- TBL_HISTORY �� TBL_CAFE
ALTER TABLE TBL_HISTORY
ADD CONSTRAINT FK_HISTORY_CAFE FOREIGN KEY (HISTORY_CAFE_NO)
REFERENCES TBL_CAFE (CAFE_NO);

-- TBL_HISTORY �� TBL_TICKET
ALTER TABLE TBL_HISTORY
ADD CONSTRAINT FK_HISTORY_TICKET FOREIGN KEY (HISTORY_TICKET_ID)
REFERENCES TBL_TICKET (TICKET_ID);

-- TBL_HISTORY �� TBL_USER
ALTER TABLE TBL_HISTORY
ADD CONSTRAINT FK_HISTORY_USER FOREIGN KEY (HISTORY_USER_ID)
REFERENCES TBL_USER (USER_ID);

-- TBL_USER_REPORT �� TBL_USER
ALTER TABLE TBL_USER_REPORT
ADD CONSTRAINT FK_USER_REPORT_USER FOREIGN KEY (REPORTER_ID)
REFERENCES TBL_USER (USER_ID);

-- TBL_USER_REPORT �� TBL_COMMENT
ALTER TABLE TBL_USER_REPORT
ADD CONSTRAINT FK_USER_REPORT_COMMENT FOREIGN KEY (TARGET_COMMENT_ID)
REFERENCES TBL_COMMENT (COMMENT_ID);

-- TBL_USER_REPORT �� TBL_CODE
ALTER TABLE TBL_USER_REPORT
ADD CONSTRAINT FK_USER_REPORT_CODE FOREIGN KEY (REPORT_CODE_ID)
REFERENCES TBL_CODE (CODE_ID);

-- TBL_IMAGE �� TBL_CAFE
ALTER TABLE TBL_IMAGE
ADD CONSTRAINT FK_IMAGE_CAFE FOREIGN KEY (CAFE_NO)
REFERENCES TBL_CAFE (CAFE_NO);

-- TBL_HOST_REQUEST �� TBL_CODE
ALTER TABLE TBL_HOST_REQUEST
ADD CONSTRAINT FK_HOST_REQUEST_CODE FOREIGN KEY (REJECT_ID)
REFERENCES TBL_CODE (CODE_ID);

-- TBL_HOST_REQUEST �� TBL_CAFE
ALTER TABLE TBL_HOST_REQUEST
ADD CONSTRAINT FK_HOST_REQUEST_CAFE FOREIGN KEY (HOST_NO)
REFERENCES TBL_CAFE (CAFE_NO);

-- TBL_COMMENT �� TBL_USER
ALTER TABLE TBL_COMMENT
ADD CONSTRAINT FK_COMMENT_USER FOREIGN KEY (COMMENT_USER_ID)
REFERENCES TBL_USER (USER_ID);

-- TBL_COMMENT �� TBL_CAFE
ALTER TABLE TBL_COMMENT
ADD CONSTRAINT FK_COMMENT_CAFE FOREIGN KEY (COMMENT_CAFE_NO)
REFERENCES TBL_CAFE (CAFE_NO);

-- TBL_PAY_HISTORY �� TBL_USER
ALTER TABLE TBL_PAY_HISTORY
ADD CONSTRAINT FK_PAY_USER FOREIGN KEY (PAY_USER_ID)
REFERENCES TBL_USER (USER_ID);


--������ ����
-- TBL_PAY_HISTORY
CREATE SEQUENCE SEQ_TBL_PAY_HISTORY
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TBL_TICKET
CREATE SEQUENCE SEQ_TBL_TICKET
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TBL_TICKET_HIST
CREATE SEQUENCE SEQ_TBL_TICKET_HIST
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TBL_CAFE
CREATE SEQUENCE SEQ_TBL_CAFE
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TBL_HISTORY
CREATE SEQUENCE SEQ_TBL_HISTORY
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TBL_USER_REPORT
CREATE SEQUENCE SEQ_TBL_USER_REPORT
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TBL_IMAGE
CREATE SEQUENCE SEQ_TBL_IMAGE
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TBL_HOST_REQUEST
CREATE SEQUENCE SEQ_TBL_HOST_REQUEST
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TBL_COMMENT
CREATE SEQUENCE SEQ_TBL_COMMENT
START WITH 1
INCREMENT BY 1
NOCACHE;

//�ڵ�ȭ Ʈ���� ������
--TBL_PAY_HISTORY
CREATE OR REPLACE TRIGGER TRG_TBL_PAY_HISTORY_PK
BEFORE INSERT ON TBL_PAY_HISTORY
FOR EACH ROW
BEGIN
    IF :NEW.PAY_ID IS NULL THEN
        SELECT SEQ_TBL_PAY_HISTORY.NEXTVAL INTO :NEW.PAY_ID FROM DUAL;
    END IF;
END;
/

-- TBL_TICKET
CREATE OR REPLACE TRIGGER TRG_TBL_TICKET_PK
BEFORE INSERT ON TBL_TICKET
FOR EACH ROW
BEGIN
    IF :NEW.TICKET_ID IS NULL THEN
        SELECT SEQ_TBL_TICKET.NEXTVAL INTO :NEW.TICKET_ID FROM DUAL;
    END IF;
END;
/

-- TBL_TICKET_HIST
CREATE OR REPLACE TRIGGER TRG_TBL_TICKET_HIST_PK
BEFORE INSERT ON TBL_TICKET_HIST
FOR EACH ROW
BEGIN
    IF :NEW.HIST_CHANGE_NUMBER IS NULL THEN
        SELECT SEQ_TBL_TICKET_HIST.NEXTVAL INTO :NEW.HIST_CHANGE_NUMBER FROM DUAL;
    END IF;
END;
/

-- TBL_CAFE
CREATE OR REPLACE TRIGGER TRG_TBL_CAFE_PK
BEFORE INSERT ON TBL_CAFE
FOR EACH ROW
BEGIN
    IF :NEW.CAFE_NO IS NULL THEN
        SELECT SEQ_TBL_CAFE.NEXTVAL INTO :NEW.CAFE_NO FROM DUAL;
    END IF;
END;
/

-- TBL_HISTORY
CREATE OR REPLACE TRIGGER TRG_TBL_HISTORY_PK
BEFORE INSERT ON TBL_HISTORY
FOR EACH ROW
BEGIN
    IF :NEW.HISTORY_ID IS NULL THEN
        SELECT SEQ_TBL_HISTORY.NEXTVAL INTO :NEW.HISTORY_ID FROM DUAL;
    END IF;
END;
/

-- TBL_USER_REPORT
CREATE OR REPLACE TRIGGER TRG_TBL_USER_REPORT_PK
BEFORE INSERT ON TBL_USER_REPORT
FOR EACH ROW
BEGIN
    IF :NEW.REPORT_ID IS NULL THEN
        SELECT SEQ_TBL_USER_REPORT.NEXTVAL INTO :NEW.REPORT_ID FROM DUAL;
    END IF;
END;
/

-- TBL_IMAGE
CREATE OR REPLACE TRIGGER TRG_TBL_IMAGE_PK
BEFORE INSERT ON TBL_IMAGE
FOR EACH ROW
BEGIN
    IF :NEW.IMAGE_NO IS NULL THEN
        SELECT SEQ_TBL_IMAGE.NEXTVAL INTO :NEW.IMAGE_NO FROM DUAL;
    END IF;
END;
/

-- TBL_HOST_REQUEST
CREATE OR REPLACE TRIGGER TRG_TBL_HOST_REQUEST_PK
BEFORE INSERT ON TBL_HOST_REQUEST
FOR EACH ROW
BEGIN
    IF :NEW.APPLY_NO IS NULL THEN
        SELECT SEQ_TBL_HOST_REQUEST.NEXTVAL INTO :NEW.APPLY_NO FROM DUAL;
    END IF;
END;
/


-- TBL_COMMENT
CREATE OR REPLACE TRIGGER TRG_TBL_COMMENT_PK
BEFORE INSERT ON TBL_COMMENT
FOR EACH ROW
BEGIN
    IF :NEW.COMMENT_ID IS NULL THEN
        SELECT SEQ_TBL_COMMENT.NEXTVAL INTO :NEW.COMMENT_ID FROM DUAL;
    END IF;
END;
/

-- �������� ����
--tbl_user ���� cascade ����
-- ���� �ܷ�Ű ����
ALTER TABLE TBL_PAY_HISTORY DROP CONSTRAINT FK_PAY_USER;
ALTER TABLE TBL_COMMENT DROP CONSTRAINT FK_COMMENT_USER;
ALTER TABLE TBL_CAFE DROP CONSTRAINT FK_CAFE_HOST;
ALTER TABLE TBL_USER_REPORT DROP CONSTRAINT FK_USER_REPORT_USER;
ALTER TABLE TBL_HISTORY DROP CONSTRAINT FK_HISTORY_USER;

-- ON DELETE CASCADE�� �����
ALTER TABLE TBL_PAY_HISTORY
ADD CONSTRAINT FK_PAY_USER FOREIGN KEY (PAY_USER_ID)
REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE;

ALTER TABLE TBL_COMMENT
ADD CONSTRAINT FK_COMMENT_USER FOREIGN KEY (COMMENT_USER_ID)
REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE;

ALTER TABLE TBL_CAFE
ADD CONSTRAINT FK_CAFE_HOST FOREIGN KEY (HOST_ID)
REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE;

ALTER TABLE TBL_USER_REPORT
ADD CONSTRAINT FK_USER_REPORT_USER FOREIGN KEY (REPORTER_ID)
REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE;

ALTER TABLE TBL_HISTORY
ADD CONSTRAINT FK_HISTORY_USER FOREIGN KEY (HISTORY_USER_ID)
REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE;

--tbl_cafe ���� cascade ����
-- ���� �ܷ�Ű ����
ALTER TABLE TBL_TICKET DROP CONSTRAINT FK_TICKET_CAFE;
ALTER TABLE TBL_HISTORY DROP CONSTRAINT FK_HISTORY_CAFE;
ALTER TABLE TBL_IMAGE DROP CONSTRAINT FK_IMAGE_CAFE;
ALTER TABLE TBL_COMMENT DROP CONSTRAINT FK_COMMENT_CAFE;
ALTER TABLE TBL_HOST_REQUEST DROP CONSTRAINT FK_HOST_REQUEST_CAFE;

-- ON DELETE CASCADE�� �����
ALTER TABLE TBL_TICKET
ADD CONSTRAINT FK_TICKET_CAFE FOREIGN KEY (CAFE_NO)
REFERENCES TBL_CAFE (CAFE_NO) ON DELETE CASCADE;

ALTER TABLE TBL_HISTORY
ADD CONSTRAINT FK_HISTORY_CAFE FOREIGN KEY (HISTORY_CAFE_NO)
REFERENCES TBL_CAFE (CAFE_NO) ON DELETE CASCADE;

ALTER TABLE TBL_IMAGE
ADD CONSTRAINT FK_IMAGE_CAFE FOREIGN KEY (CAFE_NO)
REFERENCES TBL_CAFE (CAFE_NO) ON DELETE CASCADE;

ALTER TABLE TBL_COMMENT
ADD CONSTRAINT FK_COMMENT_CAFE FOREIGN KEY (COMMENT_CAFE_NO)
REFERENCES TBL_CAFE (CAFE_NO) ON DELETE CASCADE;

ALTER TABLE TBL_HOST_REQUEST
ADD CONSTRAINT FK_HOST_REQUEST_CAFE FOREIGN KEY (HOST_NO)
REFERENCES TBL_CAFE (CAFE_NO) ON DELETE CASCADE;

ALTER TABLE TBL_USER_REPORT DROP CONSTRAINT FK_USER_REPORT_COMMENT;

-- (�߰�)TBL_USER_REPORT �� TBL_COMMENT
ALTER TABLE TBL_USER_REPORT
ADD CONSTRAINT FK_USER_REPORT_COMMENT FOREIGN KEY (TARGET_COMMENT_ID)
REFERENCES TBL_COMMENT (COMMENT_ID) ON DELETE CASCADE;

--�θ��� ������ �ڽ� ��۵� ����
ALTER TABLE TBL_COMMENT
ADD CONSTRAINT FK_COMMENT_PARENT
FOREIGN KEY (COMMENT_PARENT)
REFERENCES TBL_COMMENT (COMMENT_ID)
ON DELETE CASCADE;

Alter table tbl_code modify code_parent null;

ALTER TABLE tbl_history
ADD pay_id NUMBER;

ALTER TABLE tbl_history
MODIFY pay_id NUMBER NOT NULL;

ALTER TABLE tbl_history
ADD CONSTRAINT fk_pay_id
FOREIGN KEY (pay_id)
REFERENCES tbl_pay_history(pay_id);

-- ��ü �Ұ� ����
BEGIN
   FOR i IN 1..97 LOOP
      UPDATE tbl_cafe
      SET cafe_intro_detail = 
         CASE TRUNC(DBMS_RANDOM.VALUE(1, 11)) -- 1~10 ���� ����
            WHEN 1 THEN '����� �����⿡�� �����ο� �ð��� ��� �� �ִ� ī���Դϴ�.'
            WHEN 2 THEN '�������� ���׸���� ����� Ŀ�ǰ� �ŷ����� �����Դϴ�.'
            WHEN 3 THEN '������ �������� ���γ� ������ �ϱ� ���� ������ ����Դϴ�.'
            WHEN 4 THEN '�ż��� ���ο� ���� ������ ����Ʈ�� �غ�Ǿ� �ֽ��ϴ�.'
            WHEN 5 THEN '�ڿ� ä���� ������ �ƴ��� ī�信�� �����ϼ���.'
            WHEN 6 THEN 'Ʈ������ ������� �پ��� ���� �޴��� �ڶ��Դϴ�.'
            WHEN 7 THEN 'ģ������ ����, ȥ�ڸ��� ��� ��� ��︮�� �����Դϴ�.'
            WHEN 8 THEN '���� ������ ����Ŀ���� �Բ� Ŀ�� �� ���� ������ ����������.'
            WHEN 9 THEN '���̷ο� ���ǰ� �Բ� �Ϸ縦 �������ϱ� ���� ī���Դϴ�.'
            WHEN 10 THEN '������ ���ϰ� �ӹ� �� �ִ� ������ ������ �����մϴ�.'
         END
      WHERE cafe_no = i;
   END LOOP;
   COMMIT;
END;
/