--테이블 생성
CREATE TABLE TBL_TICKET (
    TICKET_ID VARCHAR2(10) NOT NULL,
    TICKET_TYPE VARCHAR2(20) NOT NULL,
    TICKET_HOUR VARCHAR2(20) NOT NULL,
    TICKET_PRICE VARCHAR2(20) NOT NULL,
    TICKET_REG_DATE DATE NOT NULL,
    CAFE_NO VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN TBL_TICKET.TICKET_ID IS '이용권 아이디';
COMMENT ON COLUMN TBL_TICKET.TICKET_TYPE IS '이용권 종류';
COMMENT ON COLUMN TBL_TICKET.TICKET_HOUR IS '이용권 시간';
COMMENT ON COLUMN TBL_TICKET.TICKET_PRICE IS '이용권 가격';
COMMENT ON COLUMN TBL_TICKET.TICKET_REG_DATE IS '이용권 등록일';
COMMENT ON COLUMN TBL_TICKET.CAFE_NO IS '업체번호';

ALTER TABLE TBL_TICKET ADD CONSTRAINT PK_TBL_TICKET PRIMARY KEY (TICKET_ID);


CREATE TABLE TBL_CODE (
    CODE_ID VARCHAR2(30) NOT NULL,
    CODE_NAME VARCHAR2(30) NOT NULL,
    CODE_PARENT VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN TBL_CODE.CODE_ID IS '코드아이디';
COMMENT ON COLUMN TBL_CODE.CODE_NAME IS '코드명';
COMMENT ON COLUMN TBL_CODE.CODE_PARENT IS '부모코드아이디';

ALTER TABLE TBL_CODE ADD CONSTRAINT PK_TBL_CODE PRIMARY KEY (CODE_ID);


CREATE TABLE TBL_TICKET_HIST (
    HIST_CHANGE_NUMBER VARCHAR2(10) NOT NULL,
    HIST_TICKET_PRICE VARCHAR2(10) NOT NULL,
    HIST_TICKET_TIME VARCHAR2(10) NOT NULL,
    HIST_TICKET_CHANGE_DATE DATE NOT NULL,
    HIST_TICKET_ID VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN TBL_TICKET_HIST.HIST_CHANGE_NUMBER IS '변동번호';
COMMENT ON COLUMN TBL_TICKET_HIST.HIST_TICKET_PRICE IS '변경 전 가격';
COMMENT ON COLUMN TBL_TICKET_HIST.HIST_TICKET_TIME IS '변경 전 시간';
COMMENT ON COLUMN TBL_TICKET_HIST.HIST_TICKET_CHANGE_DATE IS '변경일자';
COMMENT ON COLUMN TBL_TICKET_HIST.HIST_TICKET_ID IS '이용권 아이디';

ALTER TABLE TBL_TICKET_HIST ADD CONSTRAINT PK_TBL_TICKET_HIST PRIMARY KEY (HIST_CHANGE_NUMBER);


CREATE TABLE TBL_CAFE (
    CAFE_NO VARCHAR2(10) NOT NULL,
    CAFE_NAME VARCHAR2(100) NOT NULL,
    CAFE_PHONE VARCHAR2(13) NOT NULL,
    CAFE_ADDR VARCHAR2(200) NOT NULL,
    CAFE_BIZNUM CHAR(12) NOT NULL,
    CAFE_INTRODUCE VARCHAR2(600) NOT NULL,
    CAFE_START_HOUR VARCHAR2(50) NOT NULL,
    CAFE_END_HOUR VARCHAR2(50) NOT NULL,
    CAFE_STATUS CHAR(1) DEFAULT 'N' NOT NULL,
    CAFE_INTRO_DETAIL VARCHAR2(500) NOT NULL,
    HOST_ID VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN TBL_CAFE.CAFE_NO IS '업체번호';
COMMENT ON COLUMN TBL_CAFE.CAFE_NAME IS '업체명';
COMMENT ON COLUMN TBL_CAFE.CAFE_PHONE IS '카페 전화번호';
COMMENT ON COLUMN TBL_CAFE.CAFE_ADDR IS '업체 주소';
COMMENT ON COLUMN TBL_CAFE.CAFE_BIZNUM IS '사업자 등록 번호';
COMMENT ON COLUMN TBL_CAFE.CAFE_INTRODUCE IS '소개글';
COMMENT ON COLUMN TBL_CAFE.CAFE_START_HOUR IS '영업 시작 시간';
COMMENT ON COLUMN TBL_CAFE.CAFE_END_HOUR IS '영업 종료 시간';
COMMENT ON COLUMN TBL_CAFE.CAFE_STATUS IS '운영여부(Y,N)';
COMMENT ON COLUMN TBL_CAFE.CAFE_INTRO_DETAIL IS '공간소개';
COMMENT ON COLUMN TBL_CAFE.HOST_ID IS '호스트아이디';

ALTER TABLE TBL_CAFE ADD CONSTRAINT PK_TBL_CAFE PRIMARY KEY (CAFE_NO);


CREATE TABLE TBL_HISTORY (
    HISTORY_ID VARCHAR2(10) NOT NULL,
    HISTORY_START DATE NOT NULL,
    HISTORY_END DATE NOT NULL,
    HISTORY_CAFE_NO VARCHAR2(10) NOT NULL,
    HISTORY_SEAT_NO VARCHAR2(10) NOT NULL,
    HISTORY_TICKET_ID VARCHAR2(10) NOT NULL,
    HISTORY_USER_ID VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN TBL_HISTORY.HISTORY_ID IS '고유번호';
COMMENT ON COLUMN TBL_HISTORY.HISTORY_START IS '사용시작일자';
COMMENT ON COLUMN TBL_HISTORY.HISTORY_END IS '사용 종료일자';
COMMENT ON COLUMN TBL_HISTORY.HISTORY_CAFE_NO IS '업체번호';
COMMENT ON COLUMN TBL_HISTORY.HISTORY_SEAT_NO IS '좌석번호';
COMMENT ON COLUMN TBL_HISTORY.HISTORY_TICKET_ID IS '이용권 아이디';
COMMENT ON COLUMN TBL_HISTORY.HISTORY_USER_ID IS '일반 사용자 아이디';

ALTER TABLE TBL_HISTORY ADD CONSTRAINT PK_TBL_HISTORY PRIMARY KEY (HISTORY_ID);


CREATE TABLE TBL_USER_REPORT (
    REPORT_ID VARCHAR2(20) NOT NULL,
    REPORTER_ID VARCHAR2(10) NOT NULL,
    TARGET_COMMENT_ID VARCHAR2(20) NOT NULL,
    REPORT_CODE_ID VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN TBL_USER_REPORT.REPORT_ID IS '신고번호';
COMMENT ON COLUMN TBL_USER_REPORT.REPORTER_ID IS '이용자 아이디';
COMMENT ON COLUMN TBL_USER_REPORT.TARGET_COMMENT_ID IS '글 아이디';
COMMENT ON COLUMN TBL_USER_REPORT.REPORT_CODE_ID IS '신고사유코드';

ALTER TABLE TBL_USER_REPORT ADD CONSTRAINT PK_TBL_USER_REPORT PRIMARY KEY (REPORT_ID);


CREATE TABLE TBL_IMAGE (
    IMAGE_NO VARCHAR2(10) NOT NULL,
    CAFE_NO VARCHAR2(10) NOT NULL,
    IMAGE_NAME VARCHAR2(200) NOT NULL,
    IMAGE_PATH VARCHAR2(300) NOT NULL
);

COMMENT ON COLUMN TBL_IMAGE.IMAGE_NO IS '이미지 번호';
COMMENT ON COLUMN TBL_IMAGE.CAFE_NO IS '업체번호';
COMMENT ON COLUMN TBL_IMAGE.IMAGE_NAME IS '이미지 파일 이름';
COMMENT ON COLUMN TBL_IMAGE.IMAGE_PATH IS '이미지 경로';

ALTER TABLE TBL_IMAGE ADD CONSTRAINT PK_TBL_IMAGE PRIMARY KEY (IMAGE_NO);


CREATE TABLE TBL_HOST_REQUEST (
    APPLY_NO NUMBER NOT NULL,
    APPLY_DATE DATE NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'N' NOT NULL,
    REJECT_ID VARCHAR2(30) NULL,
    HOST_NO VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN TBL_HOST_REQUEST.APPLY_NO IS '신청번호';
COMMENT ON COLUMN TBL_HOST_REQUEST.APPLY_DATE IS '신청일';
COMMENT ON COLUMN TBL_HOST_REQUEST.STATUS IS '승인여부(Y,N)';
COMMENT ON COLUMN TBL_HOST_REQUEST.REJECT_ID IS '반려사유코드';
COMMENT ON COLUMN TBL_HOST_REQUEST.HOST_NO IS '업체 번호';

ALTER TABLE TBL_HOST_REQUEST ADD CONSTRAINT PK_TBL_HOST_REQUEST PRIMARY KEY (APPLY_NO);


CREATE TABLE TBL_USER (
    USER_ID VARCHAR2(10) NOT NULL,
    USER_PW VARCHAR2(12) NOT NULL,
    USER_ROLE NUMBER DEFAULT 3 NOT NULL,
    USER_PHONE VARCHAR2(13) NOT NULL,
    USER_STATUS CHAR(1) DEFAULT 'N' NOT NULL,
    USER_IMAGE VARCHAR2(100)
);

COMMENT ON COLUMN TBL_USER.USER_ID IS '이용자 아이디';
COMMENT ON COLUMN TBL_USER.USER_PW IS '이용자 비밀번호';
COMMENT ON COLUMN TBL_USER.USER_ROLE IS '이용자 권한';
COMMENT ON COLUMN TBL_USER.USER_PHONE IS '이용자 전화번호';
COMMENT ON COLUMN TBL_USER.USER_STATUS IS '호스트 신청여부';
COMMENT ON COLUMN TBL_USER.USER_IMAGE IS '이용자 프로필 사진';

ALTER TABLE TBL_USER ADD CONSTRAINT PK_TBL_USER PRIMARY KEY (USER_ID);


CREATE TABLE TBL_COMMENT (
    COMMENT_ID VARCHAR2(20) NOT NULL,
    TARGET_TYPE VARCHAR2(3) NOT NULL,
    CONTENT VARCHAR2(500) NOT NULL,
    COMMENT_TIME DATE NOT NULL,
    COMMENT_USER_ID VARCHAR2(10) NOT NULL,
    COMMENT_CAFE_NO VARCHAR2(10) NOT NULL,
    COMMENT_PARENT VARCHAR2(500)
);

COMMENT ON COLUMN TBL_COMMENT.COMMENT_ID IS '글 아이디';
COMMENT ON COLUMN TBL_COMMENT.TARGET_TYPE IS '대상유형';
COMMENT ON COLUMN TBL_COMMENT.CONTENT IS '글 내용';
COMMENT ON COLUMN TBL_COMMENT.COMMENT_TIME IS '작성시간';
COMMENT ON COLUMN TBL_COMMENT.COMMENT_USER_ID IS '이용자 아이디';
COMMENT ON COLUMN TBL_COMMENT.COMMENT_CAFE_NO IS '업체번호';
COMMENT ON COLUMN TBL_COMMENT.COMMENT_PARENT IS '부모댓글 아이디';

ALTER TABLE TBL_COMMENT ADD CONSTRAINT PK_TBL_COMMENT PRIMARY KEY (COMMENT_ID);


CREATE TABLE TBL_PAY_HISTORY (
    PAY_ID NUMBER NOT NULL,
    PAY_TIME DATE NOT NULL,
    PAY_STATUS VARCHAR2(10) NOT NULL,
    PAY_AMOUNT VARCHAR2(10) NOT NULL,
    PAY_METHOD VARCHAR2(10) NOT NULL,
    PAY_USER_ID VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN TBL_PAY_HISTORY.PAY_ID IS '결제아이디';
COMMENT ON COLUMN TBL_PAY_HISTORY.PAY_TIME IS '결제 시간';
COMMENT ON COLUMN TBL_PAY_HISTORY.PAY_STATUS IS '결제 상태';
COMMENT ON COLUMN TBL_PAY_HISTORY.PAY_AMOUNT IS '결제 금액';
COMMENT ON COLUMN TBL_PAY_HISTORY.PAY_METHOD IS '결제 수단';
COMMENT ON COLUMN TBL_PAY_HISTORY.PAY_USER_ID IS '이용자 아이디';

ALTER TABLE TBL_PAY_HISTORY ADD CONSTRAINT PK_TBL_PAY_HISTORY PRIMARY KEY (PAY_ID);

--FK 생성
-- TBL_TICKET → TBL_CAFE
ALTER TABLE TBL_TICKET
ADD CONSTRAINT FK_TICKET_CAFE FOREIGN KEY (CAFE_NO)
REFERENCES TBL_CAFE (CAFE_NO);

-- TBL_TICKET_HIST → TBL_TICKET
ALTER TABLE TBL_TICKET_HIST
ADD CONSTRAINT FK_TICKET_HIST_TICKET FOREIGN KEY (HIST_TICKET_ID)
REFERENCES TBL_TICKET (TICKET_ID);

-- TBL_CAFE → TBL_USER
ALTER TABLE TBL_CAFE
ADD CONSTRAINT FK_CAFE_HOST FOREIGN KEY (HOST_ID)
REFERENCES TBL_USER (USER_ID);

-- TBL_HISTORY → TBL_CAFE
ALTER TABLE TBL_HISTORY
ADD CONSTRAINT FK_HISTORY_CAFE FOREIGN KEY (HISTORY_CAFE_NO)
REFERENCES TBL_CAFE (CAFE_NO);

-- TBL_HISTORY → TBL_TICKET
ALTER TABLE TBL_HISTORY
ADD CONSTRAINT FK_HISTORY_TICKET FOREIGN KEY (HISTORY_TICKET_ID)
REFERENCES TBL_TICKET (TICKET_ID);

-- TBL_HISTORY → TBL_USER
ALTER TABLE TBL_HISTORY
ADD CONSTRAINT FK_HISTORY_USER FOREIGN KEY (HISTORY_USER_ID)
REFERENCES TBL_USER (USER_ID);

-- TBL_USER_REPORT → TBL_USER
ALTER TABLE TBL_USER_REPORT
ADD CONSTRAINT FK_USER_REPORT_USER FOREIGN KEY (REPORTER_ID)
REFERENCES TBL_USER (USER_ID);

-- TBL_USER_REPORT → TBL_COMMENT
ALTER TABLE TBL_USER_REPORT
ADD CONSTRAINT FK_USER_REPORT_COMMENT FOREIGN KEY (TARGET_COMMENT_ID)
REFERENCES TBL_COMMENT (COMMENT_ID);

-- TBL_USER_REPORT → TBL_CODE
ALTER TABLE TBL_USER_REPORT
ADD CONSTRAINT FK_USER_REPORT_CODE FOREIGN KEY (REPORT_CODE_ID)
REFERENCES TBL_CODE (CODE_ID);

-- TBL_IMAGE → TBL_CAFE
ALTER TABLE TBL_IMAGE
ADD CONSTRAINT FK_IMAGE_CAFE FOREIGN KEY (CAFE_NO)
REFERENCES TBL_CAFE (CAFE_NO);

-- TBL_HOST_REQUEST → TBL_CODE
ALTER TABLE TBL_HOST_REQUEST
ADD CONSTRAINT FK_HOST_REQUEST_CODE FOREIGN KEY (REJECT_ID)
REFERENCES TBL_CODE (CODE_ID);

-- TBL_HOST_REQUEST → TBL_CAFE
ALTER TABLE TBL_HOST_REQUEST
ADD CONSTRAINT FK_HOST_REQUEST_CAFE FOREIGN KEY (HOST_NO)
REFERENCES TBL_CAFE (CAFE_NO);

-- TBL_COMMENT → TBL_USER
ALTER TABLE TBL_COMMENT
ADD CONSTRAINT FK_COMMENT_USER FOREIGN KEY (COMMENT_USER_ID)
REFERENCES TBL_USER (USER_ID);

-- TBL_COMMENT → TBL_CAFE
ALTER TABLE TBL_COMMENT
ADD CONSTRAINT FK_COMMENT_CAFE FOREIGN KEY (COMMENT_CAFE_NO)
REFERENCES TBL_CAFE (CAFE_NO);

-- TBL_PAY_HISTORY → TBL_USER
ALTER TABLE TBL_PAY_HISTORY
ADD CONSTRAINT FK_PAY_USER FOREIGN KEY (PAY_USER_ID)
REFERENCES TBL_USER (USER_ID);


--시퀀스 생성
-- TBL_PAY_HISTORY
CREATE SEQUENCE SEQ_TBL_PAY_HISTORY
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TBL_TICKET
CREATE SEQUENCE SEQ_TBL_TICKET
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TBL_TICKET_HIST
CREATE SEQUENCE SEQ_TBL_TICKET_HIST
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TBL_CAFE
CREATE SEQUENCE SEQ_TBL_CAFE
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TBL_HISTORY
CREATE SEQUENCE SEQ_TBL_HISTORY
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TBL_USER_REPORT
CREATE SEQUENCE SEQ_TBL_USER_REPORT
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TBL_IMAGE
CREATE SEQUENCE SEQ_TBL_IMAGE
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TBL_HOST_REQUEST
CREATE SEQUENCE SEQ_TBL_HOST_REQUEST
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TBL_COMMENT
CREATE SEQUENCE SEQ_TBL_COMMENT
START WITH 1
INCREMENT BY 1
NOCACHE;

//자동화 트리거 생성문
--TBL_PAY_HISTORY
CREATE OR REPLACE TRIGGER TRG_TBL_PAY_HISTORY_PK
BEFORE INSERT ON TBL_PAY_HISTORY
FOR EACH ROW
BEGIN
    IF :NEW.PAY_ID IS NULL THEN
        SELECT SEQ_TBL_PAY_HISTORY.NEXTVAL INTO :NEW.PAY_ID FROM DUAL;
    END IF;
END;
/

-- TBL_TICKET
CREATE OR REPLACE TRIGGER TRG_TBL_TICKET_PK
BEFORE INSERT ON TBL_TICKET
FOR EACH ROW
BEGIN
    IF :NEW.TICKET_ID IS NULL THEN
        SELECT SEQ_TBL_TICKET.NEXTVAL INTO :NEW.TICKET_ID FROM DUAL;
    END IF;
END;
/

-- TBL_TICKET_HIST
CREATE OR REPLACE TRIGGER TRG_TBL_TICKET_HIST_PK
BEFORE INSERT ON TBL_TICKET_HIST
FOR EACH ROW
BEGIN
    IF :NEW.HIST_CHANGE_NUMBER IS NULL THEN
        SELECT SEQ_TBL_TICKET_HIST.NEXTVAL INTO :NEW.HIST_CHANGE_NUMBER FROM DUAL;
    END IF;
END;
/

-- TBL_CAFE
CREATE OR REPLACE TRIGGER TRG_TBL_CAFE_PK
BEFORE INSERT ON TBL_CAFE
FOR EACH ROW
BEGIN
    IF :NEW.CAFE_NO IS NULL THEN
        SELECT SEQ_TBL_CAFE.NEXTVAL INTO :NEW.CAFE_NO FROM DUAL;
    END IF;
END;
/

-- TBL_HISTORY
CREATE OR REPLACE TRIGGER TRG_TBL_HISTORY_PK
BEFORE INSERT ON TBL_HISTORY
FOR EACH ROW
BEGIN
    IF :NEW.HISTORY_ID IS NULL THEN
        SELECT SEQ_TBL_HISTORY.NEXTVAL INTO :NEW.HISTORY_ID FROM DUAL;
    END IF;
END;
/

-- TBL_USER_REPORT
CREATE OR REPLACE TRIGGER TRG_TBL_USER_REPORT_PK
BEFORE INSERT ON TBL_USER_REPORT
FOR EACH ROW
BEGIN
    IF :NEW.REPORT_ID IS NULL THEN
        SELECT SEQ_TBL_USER_REPORT.NEXTVAL INTO :NEW.REPORT_ID FROM DUAL;
    END IF;
END;
/

-- TBL_IMAGE
CREATE OR REPLACE TRIGGER TRG_TBL_IMAGE_PK
BEFORE INSERT ON TBL_IMAGE
FOR EACH ROW
BEGIN
    IF :NEW.IMAGE_NO IS NULL THEN
        SELECT SEQ_TBL_IMAGE.NEXTVAL INTO :NEW.IMAGE_NO FROM DUAL;
    END IF;
END;
/

-- TBL_HOST_REQUEST
CREATE OR REPLACE TRIGGER TRG_TBL_HOST_REQUEST_PK
BEFORE INSERT ON TBL_HOST_REQUEST
FOR EACH ROW
BEGIN
    IF :NEW.APPLY_NO IS NULL THEN
        SELECT SEQ_TBL_HOST_REQUEST.NEXTVAL INTO :NEW.APPLY_NO FROM DUAL;
    END IF;
END;
/


-- TBL_COMMENT
CREATE OR REPLACE TRIGGER TRG_TBL_COMMENT_PK
BEFORE INSERT ON TBL_COMMENT
FOR EACH ROW
BEGIN
    IF :NEW.COMMENT_ID IS NULL THEN
        SELECT SEQ_TBL_COMMENT.NEXTVAL INTO :NEW.COMMENT_ID FROM DUAL;
    END IF;
END;
/

-- 제약조건 수정
--tbl_user 관련 cascade 설정
-- 기존 외래키 삭제
ALTER TABLE TBL_PAY_HISTORY DROP CONSTRAINT FK_PAY_USER;
ALTER TABLE TBL_COMMENT DROP CONSTRAINT FK_COMMENT_USER;
ALTER TABLE TBL_CAFE DROP CONSTRAINT FK_CAFE_HOST;
ALTER TABLE TBL_USER_REPORT DROP CONSTRAINT FK_USER_REPORT_USER;
ALTER TABLE TBL_HISTORY DROP CONSTRAINT FK_HISTORY_USER;

-- ON DELETE CASCADE로 재생성
ALTER TABLE TBL_PAY_HISTORY
ADD CONSTRAINT FK_PAY_USER FOREIGN KEY (PAY_USER_ID)
REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE;

ALTER TABLE TBL_COMMENT
ADD CONSTRAINT FK_COMMENT_USER FOREIGN KEY (COMMENT_USER_ID)
REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE;

ALTER TABLE TBL_CAFE
ADD CONSTRAINT FK_CAFE_HOST FOREIGN KEY (HOST_ID)
REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE;

ALTER TABLE TBL_USER_REPORT
ADD CONSTRAINT FK_USER_REPORT_USER FOREIGN KEY (REPORTER_ID)
REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE;

ALTER TABLE TBL_HISTORY
ADD CONSTRAINT FK_HISTORY_USER FOREIGN KEY (HISTORY_USER_ID)
REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE;

--tbl_cafe 관련 cascade 설정
-- 기존 외래키 삭제
ALTER TABLE TBL_TICKET DROP CONSTRAINT FK_TICKET_CAFE;
ALTER TABLE TBL_HISTORY DROP CONSTRAINT FK_HISTORY_CAFE;
ALTER TABLE TBL_IMAGE DROP CONSTRAINT FK_IMAGE_CAFE;
ALTER TABLE TBL_COMMENT DROP CONSTRAINT FK_COMMENT_CAFE;
ALTER TABLE TBL_HOST_REQUEST DROP CONSTRAINT FK_HOST_REQUEST_CAFE;

-- ON DELETE CASCADE로 재생성
ALTER TABLE TBL_TICKET
ADD CONSTRAINT FK_TICKET_CAFE FOREIGN KEY (CAFE_NO)
REFERENCES TBL_CAFE (CAFE_NO) ON DELETE CASCADE;

ALTER TABLE TBL_HISTORY
ADD CONSTRAINT FK_HISTORY_CAFE FOREIGN KEY (HISTORY_CAFE_NO)
REFERENCES TBL_CAFE (CAFE_NO) ON DELETE CASCADE;

ALTER TABLE TBL_IMAGE
ADD CONSTRAINT FK_IMAGE_CAFE FOREIGN KEY (CAFE_NO)
REFERENCES TBL_CAFE (CAFE_NO) ON DELETE CASCADE;

ALTER TABLE TBL_COMMENT
ADD CONSTRAINT FK_COMMENT_CAFE FOREIGN KEY (COMMENT_CAFE_NO)
REFERENCES TBL_CAFE (CAFE_NO) ON DELETE CASCADE;

ALTER TABLE TBL_HOST_REQUEST
ADD CONSTRAINT FK_HOST_REQUEST_CAFE FOREIGN KEY (HOST_NO)
REFERENCES TBL_CAFE (CAFE_NO) ON DELETE CASCADE;

ALTER TABLE TBL_USER_REPORT DROP CONSTRAINT FK_USER_REPORT_COMMENT;

-- (추가)TBL_USER_REPORT → TBL_COMMENT
ALTER TABLE TBL_USER_REPORT
ADD CONSTRAINT FK_USER_REPORT_COMMENT FOREIGN KEY (TARGET_COMMENT_ID)
REFERENCES TBL_COMMENT (COMMENT_ID) ON DELETE CASCADE;

--부모댓글 삭제시 자식 댓글도 삭제
ALTER TABLE TBL_COMMENT
ADD CONSTRAINT FK_COMMENT_PARENT
FOREIGN KEY (COMMENT_PARENT)
REFERENCES TBL_COMMENT (COMMENT_ID)
ON DELETE CASCADE;

Alter table tbl_code modify code_parent null;

ALTER TABLE tbl_history
ADD pay_id NUMBER;

ALTER TABLE tbl_history
MODIFY pay_id NUMBER NOT NULL;

ALTER TABLE tbl_history
ADD CONSTRAINT fk_pay_id
FOREIGN KEY (pay_id)
REFERENCES tbl_pay_history(pay_id);

-- 업체 소개 수정
BEGIN
   FOR i IN 1..97 LOOP
      UPDATE tbl_cafe
      SET cafe_intro_detail = 
         CASE TRUNC(DBMS_RANDOM.VALUE(1, 11)) -- 1~10 사이 정수
            WHEN 1 THEN '편안한 분위기에서 여유로운 시간을 즐길 수 있는 카페입니다.'
            WHEN 2 THEN '감성적인 인테리어와 향긋한 커피가 매력적인 공간입니다.'
            WHEN 3 THEN '조용한 공간에서 공부나 업무를 하기 좋은 최적의 장소입니다.'
            WHEN 4 THEN '신선한 원두와 정성 가득한 디저트가 준비되어 있습니다.'
            WHEN 5 THEN '자연 채광이 가득한 아늑한 카페에서 힐링하세요.'
            WHEN 6 THEN '트렌디한 분위기와 다양한 음료 메뉴가 자랑입니다.'
            WHEN 7 THEN '친구와의 수다, 혼자만의 사색 모두 어울리는 공간입니다.'
            WHEN 8 THEN '매일 구워낸 베이커리와 함께 커피 한 잔의 여유를 느껴보세요.'
            WHEN 9 THEN '감미로운 음악과 함께 하루를 마무리하기 좋은 카페입니다.'
            WHEN 10 THEN '누구나 편하게 머물 수 있는 따뜻한 공간을 제공합니다.'
         END
      WHERE cafe_no = i;
   END LOOP;
   COMMIT;
END;
/